version: 2

# Build configuration - using supported OS values
build:
  os: ubuntu-20.04
  tools:
    python: "3.11"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Python requirements
python:
  install:
    - requirements: docs/requirements.txt

# Build documentation in additional formats
formats: all