version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Build documentation in additional formats
formats:
  - pdf
  - epub

# Set the version of Python
python:
  version: "3.11"
  install:
    - requirements: docs/requirements.txt

# Build configuration
build:
  image: latest

# Submodules configuration (if needed)
submodules:
  include: all